#!/bin/sh


image() {
	if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' \
			"$(($4 + 1))" "$(($5 + 1))" "$(($2 - 3))" "$3" "$1" >"$FIFO_UEBERZUG"
		return 1
	else
		mediainfo "$1"
	fi
}

create_cache_name() {
	echo "${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
}

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

case "$(mimetype --brief "$1")" in
	image/*)
		image "$1" "$2" "$3" "$4" "$5"
		;;
	text/troff)
		man ./ "$1" | col -b
		;;
	text/* | */xml | application/json)
		bat --terminal-width "$4" -f "$1"
		;;
	application/zip)
		atool --list -- "$1"
		;;
        audio/* | application/octet-stream)
		mediainfo "$1"
		;;
	video/*)
		CACHE="$(create_cache_name "$1").png"
		[ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
		image "$CACHE" "$2" "$3" "$4" "$5"
		;;
        */pdf)
		CACHE="$(create_cache_name "$1")"
		[ ! -f "$CACHE.png" ] && pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
		image "$CACHE.png" "$2" "$3" "$4" "$5"
		;;
	application/epub*)
		CACHE="$(create_cache_name "$1").png"
		[ ! -f "$CACHE" ] && gnome-epub-thumbnailer -s 1024 "$1" "$CACHE"
		image "$CACHE" "$2" "$3" "$4" "$5"
		;;
	application/x-mobipocket-ebook)
		CACHE="$(create_cache_name "$1").png"
		[ ! -f "$CACHE" ] && gnome-mobi-thumbnailer -s 1024 "$1" "$CACHE"
		image "$CACHE" "$2" "$3" "$4" "$5"
		;;
        *opendocument*)
		odt2txt "$1"
		;;
	*)
		bat --terminal-width "$4" -f "$1"
		;;
	# *.tgz|*.tar.gz)                tar tzf "$1"                 ;;
	# *.tar.bz2|*.tbz2)              tar tjf "$1"                 ;;
	# *.tar.txz|*.txz)               xz --list "$1"               ;;
	# *.tar)                         tar tf "$1"                  ;;
	# *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1"                ;;
	# *.rar)                         unrar l "$1"                 ;;
	# *.7z)                          7z l "$1"                    ;;
	# *.o)                           nm "$1" | less               ;;
	# *.torrent) transmission-show "$1"                           ;;
	# *.doc)                         catdoc "$1"                  ;;
	# *.docx)                        docx2txt "$1" -              ;;
esac
