#!/bin/sh


case "$(mimetype --brief "$1")" in
	text/troff)
		man ./ "$1" | col -b
		;;
	text/* | */xml | application/json)
		bat --terminal-width "$4" -f "$1"
		;;
	audio/* | application/octet-stream)
		mediainfo "$1"
		;;
	*opendocument*)
		odt2txt "$1"
		;;
	application/zip | \
	application/x-bzip | \
	application/x-bzip2 | \
	application/tar | \
	application/gzip | \
	application/java-archive | \
	application/vnd.rar | \
	application/x-7z-compressed | \
	application/x-compressed-tar)
		atool --list -- "$1"
		;;
	application/x-object)
		nm "$1"
		;;
	*)
		bat --terminal-width "$4" -f "$1"
		;;
esac
