#!/bin/sh


[ -f ~/.xprofile ] && . ~/.xprofile

# This needs to be imported in order to get gnome-keyring working
[ -f /etc/X11/xinit/xinitrc.d/50-systemd-user.sh ] && \
	. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

slock && exec startdwm
