#!/bin/sh


[ -f "${XDG_CONFIG_HOME}/X11/xprofile" ] && . "${XDG_CONFIG_HOME}/X11/xprofile"

# This needs to be imported in order to get gnome-keyring working
[ -f /etc/X11/xinit/xinitrc.d/50-systemd-user.sh ] && \
	. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

slock && exec startdwm
