#!/bin/sh
# This file is sourced by xinit/display managers before window manager is started


# System bar
dwmblocks &
nm-applet &
redshift-gtk &

# Deamons
unclutter &
udiskie &
dunst &
background &

# Peripherals
numlockx on &
xrdb -load "${XDG_CONFIG_HOME}/X11/Xresources" &

# Other
rfkill block bluetooth &
[ "$(hostname)" = 'XPS15' ] && \
	picom -b --config="${XDG_CONFIG_HOME}/picom/picom_$(hostname).conf" &
