#!/bin/bash


parse_info() {
	sed -E 's|([^/]*/?).*|\1|' <<<"$1" | uniq
}

list_top_dirs() {
	case "$1" in
		*.tar.bz2 | *.tbz2) parse_info "$(tar -tjf "$file")" ;;
		*.tar.gz | *.tgz) parse_info "$(tar -tzf "$file")" ;;
		*.tar.xz) parse_info "$(tar -tJf "$file")" ;;
		*.tar) parse_info "$(tar -tf "$file")" ;;
		*.zip) parse_info "$(zipinfo -1 "$file")" ;;
		*)
			echo "Don't know how to list '$file'" >&2
			return 1
			;;
	esac
}

extract_here() {
	case "$1" in
		*.tar.bz2 | *.tbz2) tar -xvjf "$file" ;;
		*.tar.gz | *.tgz) tar -xvzf "$file" ;;
		*.tar.xz) tar -xvJf "$file" ;;
		*.tar) tar -xvf "$file" ;;
		*.bz2) pbzip2 -d "$file" ;;
		*.gz) unpigz "$file" ;;
		*.xz) unxz --threads=0 "$file" ;;
		*.zip) unzip "$file" ;;
		*)
			echo "Don't know how to extract '$file'" >&2
			return 1
			;;
	esac
}

strip_suffix() {
	shopt -s extglob
	echo "${1%.@(tar.bz2|tbz2|tar.gz|tgz|tar.xz|tar|bz2|gz|xz|zip)}"
}

extract_to_dir() {
	(
	NEWDIR="$(basename "$(strip_suffix "$1")")"
	mkdir "$NEWDIR" && cd "$NEWDIR" || return

	if ! extract_here "$file"; then
		cd ../ && rm -rf "$NEWDIR" || return
	fi
	) || return
}

main() {
	flag=0
	for file in "$@"; do
		if [ "$(list_top_dirs "$file" | wc -l)" -le 1 ]; then
			extract_here "$file" || flag=1
		else
			extract_to_dir "$file" || flag=1
		fi
	done
	return "$flag"
}

main "$@"
