#!/usr/bin/env python3

import zipfile as zf
import re
from pathlib import Path
from argparse import ArgumentParser


parser = ArgumentParser(description='Zip files into a folder in an archive')

parser.add_argument('archive',
                    help='archive name')
parser.add_argument('file', nargs='+',
                    help='files to archive')

args = parser.parse_args()

if len(args.file) > 1:
    top_dir = Path(re.sub(r'\.[^.]*$', '', args.archive))
else:
    top_dir = Path('./')

# myfile.zip source/dir/file.txt dir/in/zip/file.txt
z = zf.ZipFile(args.archive, mode='a')
for f in args.file:
    path = Path(f)
    if path.is_dir():
        for p in path.rglob("*"):
            print(f'adding: {p}')
            z.write(p, Path(top_dir) / p)
    else:
        print(f'adding: {f}')
        z.write(f, Path(top_dir) / f)
z.close()
