#!/bin/sh


[ ! -d /sys/class/power_supply/BAT0 ] && exit 0

batteryCapacity="$(cat /sys/class/power_supply/BAT0/capacity)"
batteryStatus="$(cat /sys/class/power_supply/BAT0/status)"

case "$batteryStatus" in
	Full)
		batteryStatusIcon=''
		;;
	Charging)
		batteryStatusIcon=''
		;;
	Discharging)
		if [ "$batteryCapacity" -le 20 ]; then
			batteryStatusIcon=''
		elif [ "$batteryCapacity" -le 40 ]; then
			batteryStatusIcon=''
		elif [ "$batteryCapacity" -le 60 ]; then
			batteryStatusIcon=''
		elif [ "$batteryCapacity" -le 80 ]; then
			batteryStatusIcon=''
		else
			batteryStatusIcon=''
		fi
		;;
	*)
		batteryStatusIcon=''
		;;
esac

# Filter second battery with 0% (why is acpi displaying that?)
timeRemaining="$(acpi | grep -wvF '0%' | cut -d' ' -f5-)"

printf '%s' "$batteryStatusIcon ${batteryCapacity}%"
if [ -n "$timeRemaining" ]; then
	timeRemaining="$(echo "$timeRemaining" | sed -E 's/([[:digit:]]+):([[:digit:]]+):([[:digit:]]+).*/\1:\2/')"
	printf ' %s' "$timeRemaining"
fi
echo
