#!/bin/sh


CPU_TEMPERATURE="$(sensors | grep Package | awk '{print $4}' | tr -d '+')"
if [ "$(echo "$CPU_TEMPERATURE" | cut -d. -f1)" -ge 50 ]; then
	CPU_ICON=''
else
	CPU_ICON=''
fi
echo "$CPU_ICON $CPU_TEMPERATURE"
