#!/bin/sh


ALSA_RAW_OUTPUT="$(amixer -D pulse sget Master | grep -E '[[:digit:]]+\%')"
VOLUME_VALUE="$(echo "$ALSA_RAW_OUTPUT" | sed -E 's/.*\[([[:digit:]]+)\%].*/\1/; q')"

if [ "$VOLUME_VALUE" -eq 0 ] || echo "$ALSA_RAW_OUTPUT" | grep -Fq 'off'; then
	VOLUME_ICON=''
elif [ "$VOLUME_VALUE" -le 25 ]; then
	VOLUME_ICON=''
elif [ "$VOLUME_VALUE" -le 55 ]; then
	VOLUME_ICON=''
elif [ "$VOLUME_VALUE" -le 100 ]; then
	VOLUME_ICON=''
else
	VOLUME_ICON=''
fi

echo "$VOLUME_ICON $VOLUME_VALUE"
