#!/bin/bash


dfl-pull && \
make -C "${HOME}/.local/suckless/" checkout && \
make -C "${HOME}/.local/suckless/" install && \
sync-pkgs "${HOME}/.local/src/generated/pkglist_$(hostname).txt" && \
sync-conf -w
