#!/bin/bash


DIR_SUCKLESS="${HOME}/.local/suckless/"
REPOS_SUCKLESS=('dmenu' 'dwm' 'dwmblocks' 'slock' 'st')

# Dotfiles
git --git-dir="${HOME}/.dotfiles.git/" --work-tree="$HOME" pull

# Suckless
for repo in "${REPOS_SUCKLESS[@]}"; do
	git --git-dir="${DIR_SUCKLESS}/${repo}/.git" pull
done

# Nvim
git --git-dir="${HOME}/.config/nvim/.git" pull
