#!/bin/bash


SUCKLESS_PATH="${HOME}/.local/suckless/"
SUCKLESS_REPOS=('dmenu' 'dwm' 'dwmblocks' 'slock' 'st')

# Dotfiles
git --git-dir="${HOME}/.dotfiles.git/" --work-tree="$HOME" pull

# Suckless
for repo in "${SUCKLESS_REPOS[@]}"; do
	git --git-dir="${SUCKLESS_PATH}/${repo}/.git" pull
done

# Nvim
git --git-dir="${HOME}/.config/nvim/.git" pull
