#!/bin/bash


DIR_SUCKLESS="${HOME}/.local/suckless"
DIR_NVIM="${HOME}/.config"

DIR_SCRIPT="$(dirname "$0")"
NAME_SCRIPT="$(basename "$0")"
PATH_RSA_KEY="${HOME}/.ssh/id_rsa"

print_help() {
	echo "Usage: $NAME_SCRIPT [OPTIONS] FILE"
	echo "Configure system for optimal use"
	echo "Supply FILE as a list of packages that you want to install"
	echo
	echo "Options:"
	echo "-h, --help      Show brief help"
	echo "-t, --tlp       Install tlp (laptop battery management system)"
	exit 127
}

prompt_and_remove_path() {
	if [ -e "$1" ]; then
		printf "%s exists, overwrite? [Y/n] " "$1"
		read -r input
		if [ -z "$input" ] || [ "${input,,}" = 'y' ]; then
			sudo rm -rf "$1"
		else
			return 1
		fi
	fi
}

install_yay() {
	pacman -Qq | grep -q yay && return
	sudo pacman -Syu --needed --noconfirm git openssh base-devel || return
	(
		cd "$DIR_SCRIPT" &&
			git clone https://aur.archlinux.org/yay.git &&
			cd yay &&
			makepkg -si --needed --noconfirm &&
			cd .. &&
			rm -rf yay/ || return
	)
}

print_github_key() {
	PATH_RSA_KEY_GITHUB="${HOME}/github_key.pub"
	cp "${PATH_RSA_KEY}.pub" "${PATH_RSA_KEY_GITHUB}"
	printf '%s\n' \
		"A copy of an rsa public key has been added to ${PATH_RSA_KEY_GITHUB}" \
		"Please add this key to github.com"
}

check_rsa() {
	[ -f "$PATH_RSA_KEY" ] && return
	ssh-keygen -t rsa -b 4096 -C 'jirik.sz@gmail.com' -P '' -f "$PATH_RSA_KEY"
}

init_dotfiles_repo() {
	PATH_REPO="${HOME}/.dotfiles.git"
	prompt_and_remove_path "$PATH_REPO" || return 0
	sudo pacman -Syu --needed --noconfirm openssh git &&
		git clone --bare --recurse-submodules https://github.com/Jirixek/dotfiles.git "$PATH_REPO" &&
		git --git-dir="$PATH_REPO" --work-tree="$HOME" checkout -f &&
		git --git-dir="$PATH_REPO" config --local status.showUntrackedFiles no &&
		git --git-dir="$PATH_REPO" remote set-url origin git@github.com:Jirixek/dotfiles.git &&
		check_rsa &&
		rm -f ~/.bash_login || return
}

init_services() {
	# Bash suggestions for unknown packages
	# Bluetooth
	# Cron
	# Firefox profile in memory
	# Lock screen after suspend

	sudo systemctl enable \
		pkgfile-update.timer \
		bluetooth.service \
		cronie.service \
		fstrim.timer \
		slock@jirik.service
	exit_root=$?

	systemctl --user enable \
		psd.service \
		mpd.service \
		syncthing.service \
		geoclue-agent.service
	exit_user=$?

	return $((exit_root > exit_user ? exit_root : exit_user))
}

init_git_repos() {
	# Suckless
	REPOS_SUCKLESS=('dmenu' 'dwm' 'dwmblocks' 'slock' 'st')
	(
		cd "$DIR_SUCKLESS" || return
		for repo in "${REPOS_SUCKLESS[@]}"; do
			git clone "https://github.com/Jirixek/${repo}.git" "$repo"
			git --git-dir="$repo" remote set-url origin "git@github.com:Jirixek/${repo}.git"
		done
	)

	# Nvim
	(
		cd "$DIR_NVIM" || return
		git clone 'https://github.com/Jirixek/vim.git' 'nvim'
		git --git-dir='nvim' remote set-url origin "git@github.com:Jirixek/vim.git"
	)
}

link_dash() {
	# change sh shell to dash
	sudo ln -sf /bin/dash /bin/sh
}

add_user_to_groups() {
	sudo usermod -aG wireshark,rfkill,uucp,audio,geoclue,openvpn "$USER"
}

install_suckless_tools() {
	(
		cd "$DIR_SUCKLESS" || return
		make checkout
		make install
	)
}

move_gpg_folder() {
	cp -r "${HOME}/.gnupg/*" "${HOME}/.local/share/gnupg/"
	rm -r "${HOME}/.gnupg"
}

main() {
	if [ "$(id -u)" -eq 0 ]; then
		echo "Please don't run as root." >&2
		exit 1
	fi

	FILE_PACKAGES=""
	while [ "$#" -gt 0 ]; do
		case "$1" in
			-h | --help) print_help ;;
			-t | --tlp)
				sudo pacman -Syu --needed --noconfirm tlp tlp-rdw &&
					sudo systemctl enable tlp.service NetworkManager-dispatcher.service &&
					sudo systemctl mask systemd-rfkill.service systemd-rfkill.socket || exit
				shift
				;;
			*)
				if [ -z "$FILE_PACKAGES" ] && [ -f "$1" ]; then
					FILE_PACKAGES="$1"
				else
					print_help
				fi
				shift
				;;
		esac
	done

	[ -z "$FILE_PACKAGES" ] && print_help

	init_git_repos &&
		install_yay &&
		"$HOME"/.local/bin/sync-pkgs "$FILE_PACKAGES" &&
		"$HOME"/.local/bin/sync-conf -w &&
		init_services &&
		link_dash &&
		add_user_to_groups &&
		move_gpg_folder &&
		print_github_key || exit
}

main "$@"
