#!/usr/bin/env python3

import sys
from math import perm

# abs is to get rid of -0


def one_blue(total, blue):
    red = total - blue
    return abs(3 * perm(red, 2) * perm(blue, 1) / perm(total, 3))


def two_blue(total, blue):
    red = total - blue
    return abs(3 * perm(red, 1) * perm(blue, 2) / perm(total, 3))


def three_blue(total, blue):
    return abs(perm(blue, 3) / perm(total, 3))


def three_red(total, blue):
    red = total - blue
    return abs(perm(red, 3) / perm(total, 3))


def at_least_one_blue(total, blue):
    return 1 - three_red(total, blue)


def print_single(total, blue):
    print(f'>=1B: {100 * at_least_one_blue(total, blue):.2f}%',
          f' =1B: {100 * one_blue(total, blue):.2f}%',
          f' =2B: {100 * two_blue(total, blue):.2f}%',
          f' =3B: {100 * three_blue(total, blue):.2f}%', sep='\n')


def print_range(total, blue_lo, blue_hi):
    print(f'>=1B: {100 * at_least_one_blue(total, blue_lo):.2f} - {100 * at_least_one_blue(total, blue_hi):.2f}%',
          f' =1B: {100 * one_blue(total, blue_lo):.2f}% - {100 * one_blue(total, blue_hi):.2f}%',
          f' =2B: {100 * two_blue(total, blue_lo):.2f}% - {100 * two_blue(total, blue_hi):.2f}%',
          f' =3B: {100 * three_blue(total, blue_lo):.2f}% - {100 * three_blue(total, blue_hi):.2f}%', sep='\n')


def main():
    print('Blue - total')

    for line in sys.stdin:
        try:
            if line.rstrip('\n') == 'quit' or line.rstrip('\n') == 'q':
                break

            blue_str, total_str = line.split(' ')

            if '-' in blue_str:
                blue_lo_str, blue_hi_str = blue_str.split('-')
                print_range(int(total_str), int(blue_lo_str), int(blue_hi_str))
            else:
                print_single(int(total_str), int(blue_str))
        except ValueError:
            print('Invalid value')


if __name__ == '__main__':
    main()
