#!/usr/bin/env python3

import unidecode
import sys


if len(sys.argv) != 1:
    print(f'Usage: {sys.argv[0]}',
          '\tText is read from stdin.',
          file=sys.stderr)

for line in sys.stdin:
    print(unidecode.unidecode(line), end='')
