#!/bin/bash


FILE_PKGS_COMMON="$(dirname "$0")/../src/generated/pkglist_common.txt"
FILE_PKGS_HOST_SPECIFIC="$(dirname "$0")/../src/generated/pkglist_${HOSTNAME}.txt"
FILE_FILTER="$(dirname "$0")/../src/pkglistignore.txt"

get_help() {
	echo "Usage: $(basename "$0") [OPTIONS] [FILES]"
	echo "Auxiliary script to help manage pkglist."
	echo
	echo "Options:"
	echo "-g [INPUT] [OUTPUT]      Generate file without drivers and other machine specific packages"
	echo "-f|--filter              Apply filter defined in $FILE_FILTER"
	echo "[SOURCE]                 Install packages that are missing on local system acording to given file"
	exit 127
}

install_pkgs() {
	[ -n "$*" ] && echo "$@" | yay -Syu --needed "${install_flags[@]}" -
}

uninstall_pkgs() {
	[ -n "$*" ] && echo "$@" | sudo pacman -Rnus -
}

[ ! -d "$(dirname "$FILE_PKGS_OUTPUT")" ] && get_help

PKGS_CURRENT="$(pacman -Qqe | sort)"
install_flags=()
do_apply_filter='false'
while [ "$#" -gt 0 ]; do
	case "$1" in
		-h)	get_help ;;
		-g)
			comm --check-order -23 <(echo "$PKGS_CURRENT") "$FILE_PKGS_COMMON" >"$FILE_PKGS_HOST_SPECIFIC"
			exit
			;;
		--noconfirm)
			install_flags=("${install_flags[@]}" "$1")
			shift
			;;
		*)
			if [ -f "$1" ]; then
				FILE_PKGS_TARGET=("${FILE_PKGS_TARGET[@]}" "$1")
			else
				get_help
			fi
			shift
			;;
	esac
done

for file in "${FILE_PKGS_TARGET[@]}"; do
	[ ! -f "$file" ] && get_help
done
PKGS_TARGET="$(cat ${FILE_PKGS_TARGET[@]})"

pkgs_to_uninstall="$(comm --check-order -23 <(echo "$PKGS_CURRENT") <(sort <<<"$PKGS_TARGET"))"
pkgs_to_install="$(comm --check-order -23 <(sort <<<"$PKGS_TARGET") <(echo "$PKGS_CURRENT"))"

uninstall_pkgs "$pkgs_to_uninstall"
exit_uninstall=$?
install_pkgs "$pkgs_to_install"
exit_install=$?

exit $((exit_install > exit_uninstall ? exit_install : exit_uninstall))
