#!/bin/bash


HOSTNAME_FILE="$(dirname "$0")/../src/generated/pkglist_${HOSTNAME}.txt"
IGNORE_FILE="$(dirname "$0")/../src/pkglistignore.txt"

get_help() {
	echo "Usage: $(basename "$0") [OPTIONS] [FILES]"
	echo "Auxiliary script to help manage ./src/generated/pkglist_\${HOSTNAME}.txt"
	echo
	echo "Options:"
	echo "-g [INPUT] [OUTPUT]      Generate file without drivers and other machine specifis packages"
	echo "-f|--filter              Apply filter defined in .local/src/pkglistignore.txt"
	echo "[SOURCE]                 Install packages that are missing on local system acording to given file"
	exit 127
}

install_pkgs () {
	[ -n "$1" ] && echo "$1" | yay -Syu --needed "${install_flags[@]}" -
}

uninstall_pkgs () {
	[ -n "$1" ] && echo "$1" | sudo pacman -Rnus -
}

filter_pkgs () {
	filter="$(sed 's/.*/\/&\/d;/' "$IGNORE_FILE")"
	sed -E "$filter"
}

[ ! -d "$(dirname "$HOSTNAME_FILE")" ] && get_help

current_pkgs="$(pacman -Qqe | sort)"
install_flags=()
apply_filter='false'
while [ "$#" -gt 0 ]; do
	case "$1" in
		-h)	get_help ;;
		-f|--filter)
			apply_filter='true'
			shift
			;;
		-g)
			echo "$current_pkgs" > "$HOSTNAME_FILE"
			exit
			;;
		--noconfirm)
			install_flags=("${install_flags[@]}" "$1")
			shift
			;;
		*)
			if [ -f "$1" ]; then
				target_file="$1"
			else
				get_help
			fi
			shift
			;;
	esac
done

[ ! -f "$target_file" ] && get_help

filter_function="$([ "$apply_filter" = true ] && echo 'filter_pkgs' || echo 'cat')"

new_pkgs="$(comm -13 <(sort <<<"$current_pkgs") <(sort "$target_file") | "$filter_function")"
old_pkgs="$(comm -23 <(sort <<<"$current_pkgs") <(sort "$target_file") | "$filter_function")"

install_pkgs "$new_pkgs"
install_exit=$?
uninstall_pkgs "$old_pkgs"
uninstall_exit=$?

exit $((install_exit > uninstall_exit ? install_exit : uninstall_exit))
