#!/bin/bash


FILE_PKGS_OUTPUT="$(dirname "$0")/../src/generated/pkglist_${HOSTNAME}.txt"
FILE_FILTER="$(dirname "$0")/../src/pkglistignore.txt"

get_help() {
	echo "Usage: $(basename "$0") [OPTIONS] [FILES]"
	echo "Auxiliary script to help manage $FILE_PKGS_OUTPUT"
	echo
	echo "Options:"
	echo "-g [INPUT] [OUTPUT]      Generate file without drivers and other machine specific packages"
	echo "-f|--filter              Apply filter defined in $FILE_FILTER"
	echo "[SOURCE]                 Install packages that are missing on local system acording to given file"
	exit 127
}

install_pkgs() {
	[ -n "$1" ] && echo "$1" | yay -Syu --needed "${install_flags[@]}" -
}

uninstall_pkgs() {
	[ -n "$1" ] && echo "$1" | sudo pacman -Rnus -
}

filter_pkgs() {
	filter="$(sed 's/.*/\/&\/d;/' "$FILE_FILTER")"
	sed -E "$filter"
}

[ ! -d "$(dirname "$FILE_PKGS_OUTPUT")" ] && get_help

PKGS_CURRENT="$(pacman -Qqe | sort)"
install_flags=()
do_apply_filter='false'
while [ "$#" -gt 0 ]; do
	case "$1" in
		-h)	get_help ;;
		-f|--filter)
			do_apply_filter='true'
			shift
			;;
		-g)
			echo "$PKGS_CURRENT" > "$FILE_PKGS_OUTPUT"
			exit
			;;
		--noconfirm)
			install_flags=("${install_flags[@]}" "$1")
			shift
			;;
		*)
			if [ -f "$1" ]; then
				FILE_PKGS_TARGET="$1"
			else
				get_help
			fi
			shift
			;;
	esac
done

[ ! -f "$FILE_PKGS_TARGET" ] && get_help

if [ "$do_apply_filter" = true ]; then
	NAME_FILTER_FUNCTION='filter_pkgs'
else
	NAME_FILTER_FUNCTION='cat'
fi

pkgs_to_install="$(comm -13 <(sort <<<"$PKGS_CURRENT") <(sort "$FILE_PKGS_TARGET") | "$NAME_FILTER_FUNCTION")"
pkgs_to_uninstall="$(comm -23 <(sort <<<"$PKGS_CURRENT") <(sort "$FILE_PKGS_TARGET") | "$NAME_FILTER_FUNCTION")"

uninstall_pkgs "$pkgs_to_uninstall"
exit_uninstall=$?
install_pkgs "$pkgs_to_install"
exit_install=$?

exit $((exit_install > exit_uninstall ? exit_install : exit_uninstall))
