#!/bin/bash


while :; do
	nitrogen --no-recurse --set-zoom-fill --head=0 --random "$HOME"/Pictures/wallpapers/
	nitrogen --no-recurse --set-zoom-fill --head=1 --random "$HOME"/Pictures/wallpapers/
	sleep $((60 * 15))
done
