#!/bin/sh


CHOICE="$(printf '%s\n' 'Shutdown' 'Reboot' 'Suspend' | rofi -dmenu)"

case "$CHOICE" in
	"Shutdown") shutdown -h now    ;;
	"Reboot")   reboot             ;;
	"Suspend")  systemctl suspend  ;;
esac
