#!/bin/sh


gnome_schema="org.gnome.desktop.interface"
gtk_theme="Matcha-dark-azul"
icon_theme="Qogir-dark"
cursor_theme="Adwaita"
font_name="Noto Sans 10"
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"
