#!/bin/sh


MEDIADIR="/run/media/${USER}/"
if [ -d "$MEDIADIR" ]; then
	SELECTED="$(find "$MEDIADIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | dmenu)"
	[ -n "$SELECTED" ] && sync -f "${MEDIADIR}/$SELECTED" && umount "${MEDIADIR}/$SELECTED"
fi
