#!/bin/sh


# System bar
waybar &
nm-applet --indicator &
# redshift-gtk &

# Daemons TODO: systemd
# systemctl --user import-environment DISPLAY
# Tip: This is done automatically as part of /etc/X11/xinit/xinitrc.d/50-systemd-user.sh that comes with recent versions of systemd.
udiskie &
dunst &
# background &

# Peripherals
numlockx on &
