[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#d2d4de"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
chars = "\u001B[27;5;49~"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;50~"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;51~"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;52~"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;53~"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;54~"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;55~"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;56~"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;57~"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;48~"
key = "Key0"
mods = "Control"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 1
y = 1
